language: bash

services:
  - docker

env:
  - BASE_IMAGE_STABILITY_TAG=4.10.0
  - WEBGRIND_VER=1.5 TAGS=1.5,1,latest

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
