language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=1.5
    - BASE_IMAGE_STABILITY_TAG=4.1.0
  matrix:
    - TAG=1.5 WEBGRIND_VER=1.5

script:
  - make && make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
