language: bash

services:
- docker

env:
- BASE_IMAGE_STABILITY_TAG=4.11.11
- GIT_MERGE_SEPARATOR_DUMMY_ENV_VAR=1
- WEBGRIND_VER=1.5 TAGS=1.5,1,latest

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
